name: Generate Contribution Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake
        uses: isitreallyalive/snkgen@v3.3.0
        with:
          github_user_name: Vedant-Mathur
          outputs: |
            snake.svg?palette=github-dark&color_snake=00FF00&color_dots=#1b1f23,#0e4429,#006d32,#26a641,#39d353

      - name: Create output folder
        run: mkdir -p output

      - name: Move snake.svg to output
        run: mv snake.svg output/snake.svg

      - name: Commit and push snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update contribution snake'
          add: 'output/snake.svg'
